### ISSUE TITLE
При использовании мастера "сменить материал" ПГ едет по Y в стену (в плюс)

### ISSUE THREAD

**Issue by Avdartrom** [stereotech/STE-App-Client#178]
**Describe the bug**
Перезагрузка не помогла. Привязки к предварительной установке температуры перед запуском мастера нет.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform(please complete the following information):**
 - OS: [e.g. iOS, Android, Windows, or Screen Application]
 - Version [e.g. 1.2.0]

**Additional context**

**Comment by frylock34** [comment]
G56 было прописано в config-override
