### ISSUE TITLE
При загрузке материала с холодным экструдером мастер "смены\загрузки материала" меняет окно на нагрев

### ISSUE THREAD

**Issue by Avdartrom** [stereotech/STE-App-Client#179]
**Is your feature request related to a problem? Please describe.**
Предложение: либо увеличить допуск по колебаниям температуры в мастере до +-5С
либо ждать, когда температура "устаканится", потом давать окно с кнопками
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by frylock34** [comment]
connected with #175 , already closed
