### ISSUE TITLE
Нет доступа к флешке через интерфейс STE App

### ISSUE THREAD

**Issue by ShvetsAA** [stereotech/STE-App-Client#197]
Северсталь не подключила принтер к сети, файлы собираются гонять флешкой.

Сейчас, вставляя флешку в принтер, нельзя посмотреть файлы на ней, ни с экрана принтера, ни через браузер.

**Comment by frylock34** [comment]
1. Файлы должны находиться в корне флешки
2. Нужно попробовать включить принтер с вставленной флешкой
3. Добавить в чеклист тестирование печати с флешки

**Comment by frylock34** [comment]
Проверить подключена ли флешка в октопринте

**Comment by ShvetsAA** [comment]
"Нужно попробовать включить принтер с вставленной флешкой" - выполнено. Флешки в октопринте нет.
![usb](https://user-images.githubusercontent.com/72873347/105355079-f97bca80-5c0a-11eb-9c43-b65d8044bf90.PNG)

**Comment by ShvetsAA** [comment]
При подключении флешки к W5K (Северсталь) происходит перезагрузка RaspberryPi. (2 раза подряд так было, взято со слов Антона, подсветка не гасла при подключении, значит плата/блок питания не участвуют в этом)

**Comment by ShvetsAA** [comment]
При подключении к 5BP, светодиод флешки мигает так же как и при подключении к компьютеру (на всякий случай).

**Comment by frylock34** [comment]
Исправлен способ монтирования USB накопителей в системе
