### ISSUE TITLE
Изменить оформление комментариев в менеджерах

### ISSUE THREAD

**Issue by Avdartrom** [stereotech/STE-App-Client#212]
Нужно перенести подсказки, что делать наверх, увеличить текст, дублировать подсказку на шагах с ручным управлением.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by frylock34** [comment]
> дублировать подсказку на шагах с ручным управлением

Это что значит?
