### ISSUE TITLE
Добавить поддержку строчных букв в командах терминала

### ISSUE THREAD

**Issue by ShvetsAA** [stereotech/STE-App-Client#217]
Например, чтобы поддерживалось и "**m114**" и "**M114**"
Еще, если можно, и чтобы пробелы не учитывались, например в Octoprint можно ввести команду:
**m150r0u0b0** вместо **M150 R0 U0 B0** и она выполнится без ошибок

**Comment by frylock34** [comment]
closed by b6a9734dda26e2688e9eb0e70babd47316c26e9f
