### ISSUE TITLE
Изменение названия вкладки в веб-версии

### ISSUE THREAD

**Issue by ShvetsAA** [stereotech/STE-App-Client#228]
Вроде была уже такая просьба. При нескольких открытых вкладках в хроме, хотелось бы чтобы название было в начале вкладки:
![tab_name](https://user-images.githubusercontent.com/72873347/109798484-3b4d5700-7c34-11eb-81aa-d1b2683663f9.PNG)

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by frylock34** [comment]
Про начало строки не было, сделаем
