### ISSUE TITLE
Сброс кнопки пределов на значение по умолчанию "10" при перевороте дисплея телефона с альбомного на книжный и наоборот 

### ISSUE THREAD

**Issue by ShvetsAA** [stereotech/STE-App-Client#229]
В менеджере установки нулевой точки, на экране с кнопками правления, при выборе предела, например 1 мм, и при изменении ориентации устройства, установленное значение сбрасывается на стандартное, 10 мм. Глеб уже два раза так врезался.
Приложение до переворота:
![Screenshot_20210303-145031_STE App](https://user-images.githubusercontent.com/72873347/109802832-b9f8c300-7c39-11eb-806b-456c099621e8.jpg)
Приложение после поворота:
![Screenshot_20210303-145040_STE App](https://user-images.githubusercontent.com/72873347/109802838-ba915980-7c39-11eb-910f-d2033f903e0a.jpg)
Веб версия до поворота:
![Screenshot_20210303-145352_Chrome](https://user-images.githubusercontent.com/72873347/109802841-bb29f000-7c39-11eb-8560-bb4e1dbd23fa.jpg)
Веб версия после поворота:
![Screenshot_20210303-145401_Chrome](https://user-images.githubusercontent.com/72873347/109802842-bbc28680-7c39-11eb-9e50-46a43118e445.jpg)
Принтер - 3SH, версия прошивки - 2.1.11.DEVELOP

И еще заметил что сильно уезжает разметка этих кнопок, на скринах видно.

Как вариант лечения сброса при перевороте телефона - установить по умолчанию либо 0.1, либо 1 мм. Последствия удара будут явно меньше. Движение по 10 и 100 мм - это осознанный шаг человека, который понимает всю ответственность своего решения, поэтому пусть выбирает каждый раз заново (может быть 100 мм сделать через подтверждение? :)

**Comment by frylock34** [comment]
@ShvetsAA На будущее, делайте репорты ТОЛЬКО по веб версии т.к. приложение для андроида м.б. не актуальной версии

**Comment by ShvetsAA** [comment]
> @ShvetsAA На будущее, делайте репорты ТОЛЬКО по веб версии т.к. приложение для андроида м.б. не актуальной версии

Принято!
